### ISSUE TITLE
"Roleypoly" text in top left corner cut off when using web utility

### ISSUE THREAD

**Issue by aCuteLittleBox** [kayteh/roleypoly#1]
Example shot:
https://i.imgur.com/rxunz0s.png

Using Firefox 58.0.2 on Arch Linux

**Comment by kayteh** [comment]
Thanks for your report, there's actually two things wrong up there.

**Comment by kayteh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fix header image font for non-mac](https://trello.com/c/0NWUPfBO/12-fix-header-image-font-for-non-mac)
