### ISSUE TITLE
i don't know if something isn't working or if i'm just stupid, but how do i use this?

### ISSUE THREAD

**Issue by deasar** [kayteh/roleypoly#4]

**Comment by kayteh** [comment]
Are you trying to run your own version or the public one at https://rp.kat.cafe?

**Comment by deasar** [comment]
wow i'm not sure which one i was trying to run, but i couldn't find my way to that website at all. seems to be working now :)

**Comment by kayteh** [comment]
Awesome, thanks for your interest.
