### ISSUE TITLE
Sort Roles

### ISSUE THREAD

**Issue by JapanYoshi** [kayteh/roleypoly#6]
The order in which roles appear are inconsistent; I have 4 categories, in 2 of which the roles appear in the correct order as listed in the server settings, and in the rest of which the roles appear in the opposite order.

It would be the threshold of convenience for roles to be able to be reordered.

**Comment by kayteh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Frontend: sorting categories](https://trello.com/c/mBuEsqpN/52-frontend-sorting-categories)

**Comment by kayteh** [comment]
Sorting categories was added, but sorting roles within them might still not be. It's ordered by the position in discord's role list, ideally. If it's not, please re-open the issue!
