### ISSUE TITLE
Server Messages May Contain raw HTML for Non-managerial Users

### ISSUE THREAD

**Issue by drruruu** [kayteh/roleypoly#8]
#### Issue:
![ink (1)](https://user-images.githubusercontent.com/8763488/56410641-6a769d00-6243-11e9-8019-6e18529b40a9.png)

#### Source:
https://github.com/kayteh/roleypoly/blob/762e76dfb3a2cfaad155da72f50d2934ab6d35ff/UI/src/components/role-picker/index.js#L76-L81

#### Observations
I'm no React dev but I think this could be solved by implementing `dangerouslySetInnerHTML` in the render block.

**Comment by kayteh** [comment]
Good catch, and you're perfectly right in your assumption.
